name: CI/CD Pipeline on RHEL 9

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Ensure this matches your runner's label

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'  # Use the desired Node.js version

      - name: Remove package-lock.json (if it exists)
        run: |
          if [ -f package-lock.json ]; then
            rm package-lock.json
          fi

      - name: Install dependencies
        run: npm install  # This will regenerate package-lock.json

      - name: Build the project
        run: npm run build

      # Optional: Publish the library to npm
      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # Ensure you have set this secret
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}    # Ensure you have set this secret
